version: '3.7'

services:
  db:
    image: timescale/timescaledb-ha:pg16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=development
    volumes:
      - postgres-data:/var/lib/postgresql/data
  db-test:
    image: timescale/timescaledb-ha:pg16
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    command:
      [
        "-source",
        "file:///migrations",
        "-database",
        "postgres://postgres:password@db:5432/development?sslmode=disable",
        "up",
      ]
    links:
      - db
  migrate-test:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    command:
      [
        "-source",
        "file:///migrations",
        "-database",
        "postgres://postgres:password@db-test:5432/test?sslmode=disable",
        "up",
      ]
    links:
      - db-test
  server:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/home/alice/server
      - deno-dir-data:/home/alice/deno-dir
    ports:
      - "8080:8080"
    links:
      - db
      - db-test
      - migrate
      - migrate-test
    env_file:
      - .env

volumes:
  deno-dir-data:
  postgres-data:
