#!/bin/bash

ROOT_DIR=$(git rev-parse --show-toplevel)
TARGETS=$(git diff --name-only --staged $ROOT_DIR)

FULL_PATH_TARGETS=()
MARKDOWN_FILES=()

for target in $TARGETS
do
  if [[ $target =~ \.(js|ts|cjs|mjs|d.cts|d.mts|jsx|tsx|json|jsonc)$ && -e "$ROOT_DIR/$target" ]]; then
    FULL_PATH_TARGETS+=("$ROOT_DIR/$target")
  fi

  if [[ $target =~ \.(md|markdown)$ && -e "$ROOT_DIR/$target" ]]; then
    MARKDOWN_FILES+=("$ROOT_DIR/$target")
  fi
done

if [ ${#FULL_PATH_TARGETS[@]} -ne 0 ]; then
  biome check --apply --no-errors-on-unmatched --files-ignore-unknown=true ${FULL_PATH_TARGETS[*]}
fi

if [ ${#MARKDOWN_FILES[@]} -ne 0 ]; then
  deno fmt ${MARKDOWN_FILES[*]}
fi

git add -A /home/alice/server
git update-index --again
